import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="Hulu 2.0 clone" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Let's build hulu 2.0</h1>
      {/* header */}

      {/* nav */}

      {/* results */}
    </div>
  );
}
